### ISSUE TITLE
I found AiohttpSession can't request through a proxy

### ISSUE THREAD

**Issue by KaIKuxy** [omarryhan/aiogoogle#1]
Or just I didn't found out how to do it?

**Comment by omarryhan** [comment]
Hey,

Instead of Instantiating Aiogoogle like that:

`aiogoogle = Aiogoogle(seesion_factory=(ClientSession(proxy={...}))`

Do it like this:

`aiogoogle = Aiogoogle(seesion_factory=lambda: (ClientSession(proxy={...}))`

It's also mentioned here: https://aiogoogle.readthedocs.io/en/latest/#aiogoogle.client.Aiogoogle

**Comment by KaIKuxy** [comment]
> Hey,
> 
> Instead of Instantiating Aiogoogle like that:
> 
> `aiogoogle = Aiogoogle(seesion_factory=ClientSession(proxy={...}))`
> 
> Do it like this:
> 
> `aiogoogle = Aiogoogle(seesion_factory=lambda: ClientSession(proxy={...}))`
> 
> It's also mentioned here: https://aiogoogle.readthedocs.io/en/latest/#aiogoogle.client.Aiogoogle

got it, thank you so much
