### ISSUE TITLE
don't inherit from str + dict

### ISSUE THREAD

**Issue by thehesiod** [omarryhan/aiogoogle#17]
this is bad form and from my experience can lead to strange crashes

**Comment by thehesiod** [comment]
probably should use dataclasses + typing.NamedTuple where appropriate

**Comment by omarryhan** [comment]
I think I only inherit from `str` once (with ApiKey). I didn't change anything in the subclasses of `dict` or `str`. I only did it to have the API key and credential's attributes defined in the docs. Otherwise, I didn't change their functionality. I actually don't want the credentials to be a class, just a dumb dict/json or a string. If you notice, I don't use these models inside any of the auth managers and that's by design.
