### ISSUE TITLE
thoughts about using aioauth-client

### ISSUE THREAD

**Issue by thehesiod** [omarryhan/aiogoogle#18]
to be more modular.  They have a GoogleClient

**Comment by omarryhan** [comment]
It has AioHTTP built into it, which isn't async framework agnostic. I try to keep Aiogoogle async-framework agnostic.

Also, aioauth-client, covers simple OAuth 2 use cases and doesn't include the more complex OAuth2 methods.

Last, I try to keep this library as bare-bones and extensive as possible. Unfortunately, not all OAuth2 providers implement OAuth2 the same way. So, in order to have all OAuth2 providers under one library, you must sacrifice some of the features.
