### ISSUE TITLE
[feature] add auth caching

### ISSUE THREAD

**Issue by thehesiod** [omarryhan/aiogoogle#19]
the original google oauth2 client had token caching to avoid having to re-auth if the token was still valid.  Would be awesome if this had it as well

**Comment by omarryhan** [comment]
I don't understand. Do you mean caching to disk? The access token will remain in the `user_creds` dictionary until it expires. Before every request, the `AuthManager` checks whether or not the the `access_token` is expired (by reffering to the `expires_in` property), and if it expired, it refreshes it using the `refresh_token` that was acquired at authentication. Can you link to the piece of code that caches the user's access token?

**Comment by thehesiod** [comment]
yes to disk, or to user specified storage

**Comment by omarryhan** [comment]
Because you can't read and write to disk in async Python while being async framework agnostic. Well, technically it's possible, but it would require we create some sort of a read write interface and implement it once for every async framework.

Fortunately, all credentials in this package (so far) are just a simple dictionary or a string. So I thought it wouldn't be worth the effort. Users can do that themselves in 2 lines of code.

Does that make sense?

**Comment by thehesiod** [comment]
Writing 1k or less to disk doesn't need to be async. But I'll find the relevant code in oauth2client. Google-auth has an open issue to backport this feature from their old client. This is useful for scenarios where you need to unload the client for a period of time due to memory constraints and the reload
